#!/usr/bin/env bash
# This script displays "Best School" 10 times and adds "Hi" after the 9th iteration using a while loop and if statement

count=1
while [ $count -le 10 ]
do
  echo "Best School"
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  count=$((count + 1))
done

